version: "3"
services:
    app:
        build: 
            context: ./
            dockerfile: ./Dockerfile
        container_name: "portfolio_app"
        user: "node"
        ports:
            - "8080:8080"
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app
            - /home/node/app/node_modules
        command: "npm run serve"